/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nural
 */
import java.util.Random;
import javax.swing.JOptionPane;
public class payment2 extends javax.swing.JFrame {

    /**
     * Creates new form payment2
     */
    public payment2(String totalPrice, String qty1, String qty2, String qty3) {
        initComponents();
        tfQty1.setText(qty1);
        tfQty2.setText(qty2);
        tfQty3.setText(qty3);
        tfTotal.setText(totalPrice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        btnCode1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        tfCode1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfQty1 = new javax.swing.JTextField();
        tfQty2 = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfQty3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();

        jToggleButton2.setText("jToggleButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton3.setBackground(new java.awt.Color(255, 153, 0));
        jToggleButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setText("BACK");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 100, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 670));

        jPanel3.setBackground(new java.awt.Color(253, 203, 110));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCode1.setBackground(new java.awt.Color(255, 153, 0));
        btnCode1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCode1.setForeground(new java.awt.Color(255, 255, 255));
        btnCode1.setText("GENERATE");
        btnCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCode1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 160, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRESS CREATE BUTTON FOR CREATE PAYMENT CODE");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));
        jPanel3.add(tfCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 210, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PAKET 1");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TOTAL ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));
        jPanel3.add(tfQty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 130, 30));
        jPanel3.add(tfQty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 130, 30));
        jPanel3.add(tfTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PAKET 2");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));
        jPanel3.add(tfQty3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PAKET 3");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 510, 510));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAYMENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jToggleButton5.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jToggleButton5.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton5.setText("PAY");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        menu newMenu = new menu();
        newMenu.setVisible(true);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void btnCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCode1ActionPerformed
        // TODO add your handling code here:
            if(JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin memesan paket tersebut?","Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                Random rand = new Random();
                int acak = rand.nextInt();
                String acak1 = Integer.toString(acak);
                tfCode1.setText(acak1);
            }
            //JOptionPane.showMessageDialog(null,"Apakah anda yakin ingin memesan paket tersebut?");
            
        /*Random rand = new Random();
        int acak = rand.nextInt();
        tfCode1.setText(acak);*/
    }//GEN-LAST:event_btnCode1ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        if(tfCode1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Tekan Tombol Generate Untuk Membuat Code Pembayaran");
        }
        else {
            JOptionPane.showMessageDialog(null, "Silahkan Lakukan Pembayaran Di Kasir");
            home newHome = new home();
            newHome.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment2("","","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCode1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JTextField tfCode1;
    private javax.swing.JTextField tfQty1;
    private javax.swing.JTextField tfQty2;
    private javax.swing.JTextField tfQty3;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
